### ISSUE TITLE
Dot indexing is not supported for variables of this type

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#2]
I am trying to run SynthesizeTableCollections.m and I get the above error in fSynthesizeNovelShape.m and part_obb.m. Is there any way to fix this error?

**Comment by cravisjan97** [comment]
I was able to fix this issue. The 'bbox' variable was empty. I renamed the 'OBB' directory to 'obb'. This solved the issue as the Matlab files had 'obb' as the directory name( and not 'OBB').

**Comment by diegogb** [comment]
Hi Ravi

I'm glad that you were able to solve the issue.

Best regards,

Diego
