### ISSUE TITLE
Some missing files?

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#3]
I am trying to understand your code. I see "fGetSubDividedMeshes", "fGetAdjacencyPerShape", "fCalcScoresWithNeighbours" mentioned in the comments in fSynthesizeNewShapeCollectionP.m file. I don't see these files on the repository. Is there any way you can make this public? Thanks in advance

**Comment by diegogb** [comment]
Please check the additional code that I uploaded into the folder "PreprocessUnrevisedCode"
