### ISSUE TITLE
Question about the samplingsArray and segmentsArray in preprocessed .mat files

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#5]
Thanks for sharing the preprocessing code. I am trying to write the code for the missing parts. Firstly I am trying to write the code to get samplingsArray and segmentsArray from the mesh and segmented point cloud and I have a few questions regarding the fields. 
![segments1](https://user-images.githubusercontent.com/11577265/94042007-db4aae80-fd7f-11ea-9a8d-540abde8f17e.PNG)
I see there are 7 fields in segmentsArray and I am able to understand the first 3 fields. I read your paper and understood that the sym labels were manually annotated and can be empty (maybe I am wrong?). I don't understand the fields "segmentMainAx", "ixShape" and "facesPerSeg". I want to know what algorithm you used to segment the meshes based on the point cloud segmentation. It would be really helpful if you could shed some light on this

**Comment by diegogb** [comment]
Hi. Sorry for the delayed response. I've been extremely busy at work.

About the fields that you ask, they came from the Interactive program for Segmentation of point clouds that is described in Section 4.1 of the paper.
There are many parts of the code of this Interactive Segmentation program that I did not write, so I would have to contact my former supervisor, (and co-author of the paper), for trying to find out about whether we can share the code of that program, (which is written in C#).
Having said that: 
- I don't think you need to worry about "ixShape". This is an index of the shape that was used when several shapes were loaded from the the Interactive program.
- "segmentMainAx": This is the main axis of orientation of the segment. This value was manually annotated in the Interactive Segmentation program.
- "facesPerSeg": Again, I think you don't need to worry about this field. This was used to store the number of faces contained in each mesh segment. However, if I remember correctly, this value was used experimentally but it is not required in the synthesis process
